name: Break Glass Workflow

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Breakglass deployment to a region'
        required: true
        type: choice
        options:
          - US
          - EU

jobs:
  execute-break-glass:
    uses: kornel-kotan-sonarsource/central-actions/.github/workflows/breakglass.yml@main
    with:
      region: ${{ github.event.inputs.region }}
