name: Break Glass Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Breakglass deployment to an environment'
        required: true
        type: choice
        options:
          - US
          - EU

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}