name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log building service
        run: echo "Building the service..."

      - name: Generate build number
        id: generate-build-number
        run: echo "BUILD_NUMBER=3" >> $GITHUB_ENV