name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy ${{ inputs.environment }}
        run: echo "Deployment to ${{ inputs.environment }}"
      - name: Log Account ID
        run: echo "Account id  ${{ vars.ACCOUNT_ID }}"
