name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-eu:
    runs-on: ubuntu-latest
    environment: EU
    steps:
      - name: Deploy EU
        run: echo "Deployment to EU"

  end-to-end-testing-EU:
    runs-on: ubuntu-latest
    needs: deploy-eu
    environment: EU
    steps:
      - name: End to end testing
        run: echo "End to end test execution"

  bake-in-period:
    runs-on: ubuntu-latest
    needs: end-to-end-testing-EU
    environment: EU
    steps:
      - name: Bake in period
        run: sleep 10

  deploy-us:
    runs-on: ubuntu-latest
    needs: bake-in-period
    environment: US
    steps:
      - name: Deploy US
        run: echo "Deployment to US"

  end-to-end-testing-US:
    runs-on: ubuntu-latest
    needs: deploy-us
    environment: US
    steps:
      - name: End to end testing
        run: echo "End to end test execution US"