name: Deploy

on: [workflow_call]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy ${{ inputs.environment }}
        run: echo "Deployment to${{ inputs.environment }}"
