name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Awaiting manual approval
        run: echo "Please approve this workflow run manually."

  deploy-devs:
    runs-on: ubuntu-latest
    needs: manual-approval
    #When using steps they are always executed sequentially
    steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Deploy DEV-EU
           uses: ./composite-actions/deploy-ca
           with:
            environment: DEV-EU
         - uses: ./composite-actions/deploy-ca
           name: Deploy DEV-US
           with:
            environment: DEV-US

  deploy-staging-eu:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-devs]
    with:
      environment: STAGING-EU

  deploy-staging-us:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-devs]
    with:
      environment: STAGING-US

  deploy-prod-eu:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-staging-eu, deploy-staging-us]
    with:
      environment: PROD-EU

  test-prod-eu:
    uses: ./.github/workflows/end-to-end-test.yml
    needs: deploy-prod-eu
    with:
      environment: PROD-EU

  bake-in-eu:
    runs-on: ubuntu-latest
    needs: deploy-prod-eu
    environment: PROD-EU
    steps:
      - name: Bake in period
        run: sleep 10

  deploy-prod-us:
    uses: ./.github/workflows/deploy.yml
    needs:
      - bake-in-eu
      - test-prod-eu
    with:
      environment: PROD-US

  test-prod-us:
    uses: ./.github/workflows/end-to-end-test.yml
    needs: deploy-prod-us
    with:
      environment: PROD-EU
