name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-eu:
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: EU

  end-to-end-testing-eu:
    uses: ./.github/workflows/end-to-end-testing.yml
    needs: deploy-eu
    with:
      environment: EU

  bake-in-period:
    runs-on: ubuntu-latest
    needs: end-to-end-testing-eu
    steps:
      - name: Bake in period
        run: sleep 10

  deploy-us:
    uses: ./.github/workflows/deploy.yml
    needs: bake-in-period
    with:
      environment: US

  end-to-end-testing-us:
    uses: ./.github/workflows/end-to-end-testing.yml
    needs: deploy-us
    with:
      environment: US
