name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Awaiting manual approval
        run: echo "Please approve this workflow run manually."

  deploy-dev-eu:
    uses: ./.github/workflows/deploy.yml
    needs: manual-approval
    with:
      environment: DEV-EU

  deploy-dev-us:
    uses: ./.github/workflows/deploy.yml
    needs: manual-approval
    with:
      environment: DEV-US

  deploy-staging-eu:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-dev-eu, deploy-dev-us]
    with:
      environment: STAGING-EU

  deploy-staging-us:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-dev-eu, deploy-dev-us]
    with:
      environment: STAGING-US

  deploy-prod-eu:
    uses: ./.github/workflows/deploy.yml
    needs: [deploy-staging-eu, deploy-staging-us]
    with:
      environment: PROD-EU

  test-prod-eu:
    uses: ./.github/workflows/end-to-end-test.yml
    needs: deploy-prod-eu
    with:
      environment: PROD-EU

  bake-in-eu:
    runs-on: ubuntu-latest
    needs: deploy-prod-eu
    environment: PROD-EU
    steps:
      - name: Bake in period
        run: sleep 10

  deploy-prod-us:
    uses: ./.github/workflows/deploy.yml
    needs:
      - bake-in-eu
      - test-prod-eu
    with:
      environment: PROD-US

  test-prod-us:
    uses: ./.github/workflows/end-to-end-test.yml
    needs: deploy-prod-us
    with:
      environment: PROD-EU
