name: Deployment Workflow

on:
  check_suite:
    types:
      - completed
    branches:
      - main
  workflow_run:
    workflows: [ "CI workflow" ]
    types:
      - completed
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  multi-region-deployment:
    uses: kornel-kotan-sonarsource/central-actions/.github/workflows/standard-deployment.yml@main
