name: Deployment Workflow

on:
  check_suite:
    types:
      - completed

jobs:
  multi-region-deployment:
    uses: kornel-kotan-sonarsource/central-actions/.github/workflows/standard-deployment.yml@main
