name: Deploy to DevX

on:
  pull_request:
    types:
      - labeled

jobs:
  deploy-dev:
    if: startsWith(github.event.label.name, 'dev-')
    uses: kornel-kotan-sonarsource/central-actions/.github/workflows/deploy.yml@main
    with:
      environment: ${{ github.event.label.name }}