name: Deploy to DevX

on:
  pull_request:
    types:
      - labeled

jobs:
  deploy-dev:
    if: startsWith(github.event.label.name, 'dev-')
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event.label.name }}