name: Deploy on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  deploy-dev-4:
    if: contains(github.event.label.name, 'dev-4')
    uses: ./.github/workflows/deploy.yml
    with:
      environment: DEV-4