name: Call Reusable Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: write
  pull-requests: read

jobs:
  call-reusable-workflow:
    uses: kornel-kotan-sonarsource/central-actions/.github/workflows/test-reusable.yml@main
    with:
      workflow_file: '.github/workflows/local-another.yml'
      gh_token: ${{ secrets.GITHUB_TOKEN }}